name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

    workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
            git lfs install
            huggingface-cli lfs-enable-largefiles .
            huggingface-cli login --token $HF_TOKEN
            huggingface-cli repo create demo --type space --sdk streamlit --repo-id MohitWani/demo --write-access
            git remote set-url origin https://huggingface.co/spaces/MohitWani/demo
            git push origin main --force